#!/bin/dash
# vim:ft=sh
# Print number of emails
# Depends on: khal, inotify

# Kill all descendents on exit
trap 'exit' INT TERM
trap 'kill 0' EXIT

# Default color
if [ -z "${SBP_EMAIL_COLOR}" ] ; then
  SBP_EMAIL_COLOR='brown'
fi
# Location
if [ -z "${SBP_EMAIL_LOCATION}" ] ; then
  if [ -d "${HOME}/Documents/Mail/Gmail/Inbox/new" ] ; then
    SBP_EMAIL_LOCATION="${HOME}/Documents/Mail/Gmail/Inbox/new"
  else
    exit 1
  fi
fi

# Click commands that can be overriden through environment vars
get_actions () {
# Function to generate action list
  # Left click
  if [ -z "${SBP_EMAIL_LEFTCLICK}" ] ; then
    _left='true'
  else
    _left="${SBP_EMAIL_LEFTCLICK}"
  fi
  # Right click
  if [ -z "${SBP_EMAIL_RIGHTCLICK}" ] ; then
    _right="${TERMINAL} neomutt"
  else
    _right="${SBP_EMAIL_RIGHTCLICK}"
  fi
  # Middle click
  if [ -z "${SBP_EMAIL_MIDDLECLICK}" ] ; then
    _middle="true"
  else
    _middle="${SBP_EMAIL_MIDDLECLICK}"
  fi
  # Scroll up
  if [ -z "${SBP_EMAIL_SCROLLUP}" ] ; then
    _up='true'
  else
    _up="${SBP_EMAIL_SCROLLUP}"
  fi
  # Scroll down
  if [ -z "${SBP_EMAIL_SCROLLDOWN}" ] ; then
    _down='true'
  else
    _down="${SBP_EMAIL_SCROLLDOWN}"
  fi
  # Print json
  _jsonact="{\"middle\":\"${_middle}\""
  _jsonact="${_jsonact},\"left\":\"${_left}\",\"right\":\"${_right}\""
  echo "${_jsonact},\"up\":\"${_up}\",\"down\":\"${_down}\"}"
}

get_text () {
# Parse json text that has the fields;
# * accent: Accent color (not neccessary needed)
# * prompt: Text to display
# * prefix: Icon to display at beginning
# * suffix: Icon to display at end
# * tooltip: Expanded tooltip; maybe for future
# * dim: (Boolean) To dim module or not.
  # Get number of new emails
  _new="$(find "${SBP_EMAIL_LOCATION}" | wc -l)"
  # Format fields
  if [ "${_new}" -le 0 ] ; then
    _pre=" "
    _mute='true'
  else
    _pre=" "
    _mute='false'
  fi
  # Print JSON string
  _json="{\"prompt\":\"${_new}\",\"accent\":\"${SBP_EMAIL_COLOR}\""
  _json="${_json},\"prefix\":\"${_pre}\",\"suffix\":\"\",\"dim\":${_mute}"
  echo "${_json},\"tooltip\":\"\"}"
}

# Listener loop
listener_loop () {
  # Place inotify watch on the calendar directory, or exit gracefully
  while : ; do
    inotifywait --recursive --timeout -1 \
      --event modify --event move --event create --event delete \
      "${SBP_EMAIL_LOCATION}" >/dev/null 2>&1 || exit 2
    get_text
    # Wait a while before trying to add watch again
    sleep 5
  done
}

# Main function
case $1 in
  actions) get_actions ;;
  once) get_text ;;
  *) get_text ; listener_loop ;;
esac
