#!/bin/dash
# vim:ft=sh
# Print the currently playing song on the block
# Depends on: mpd, mpc

# Kill all descendents on exit
trap 'exit' INT TERM
trap 'kill 0' EXIT

# Default color
if [ -z "${SBP_MPD_COLOR}" ] ; then
  SBP_MPD_COLOR='orange'
fi
# Default max length
if [ -z "${SBP_MPD_MAXLEN}" ] ; then
  SBP_MPD_MAXLEN=20
fi
# Click commands that can be overriden through environment vars
get_actions () {
# Function to generate action list
  # Left click
  if [ -z "${SBP_MPD_LEFTCLICK}" ] ; then
    _left='/usr/bin/mpc toggle'
  else
    _left="${SBP_MPD_LEFTCLICK}"
  fi
  # Right click
  if [ -z "${SBP_MPD_RIGHTCLICK}" ] ; then
    _right="${TERMINAL} /usr/bin/cantata"
  else
    _right="${SBP_MPD_RIGHTCLICK}"
  fi
  # Middle click
  if [ -z "${SBP_MPD_MIDDLECLICK}" ] ; then
    _middle="true"
  else
    _middle="${SBP_MPD_MIDDLECLICK}"
  fi
  # Scroll up
  if [ -z "${SBP_MPD_SCROLLUP}" ] ; then
    _up='true'
  else
    _up="${SBP_MPD_SCROLLUP}"
  fi
  # Scroll down
  if [ -z "${SBP_MPD_SCROLLDOWN}" ] ; then
    _down='true'
  else
    _down="${SBP_MPD_SCROLLDOWN}"
  fi
  # Print json
  _jsonact="{\"middle\":\"${_middle}\""
  _jsonact="${_jsonact},\"left\":\"${_left}\",\"right\":\"${_right}\""
  echo "${_jsonact},\"up\":\"${_up}\",\"down\":\"${_down}\"}"
}

get_text () {
# Parse json text that has the fields;
# * accent: Accent color (not neccessary needed)
# * prompt: Text to display
# * prefix: Icon to display at beginning
# * suffix: Icon to display at end
# * tooltip: Expanded tooltip; maybe for future
# * dim: (Boolean) To dim module or not.
  # Get MPD info, even if it breaks
  _info="$(mpc 2>&1)"
  _tip="$(echo "${_info}" | tr '\n' '~' | sed 's|~|\\\\n|g')"
  _lines="$(echo "${_info}" | wc --lines)"
  # Default to no-dimming
  _mute='false'
  _pre=' '
  _suf=''
  _txt=''
  # Set the _txt variable in this block
  case "${_lines}" in
    3) # Case; there is a song in the list
      # Get current info
      _sta="$(echo "${_info}" | sed --quiet '2p' | awk '{print $1}')"
      _tit="$(echo "${_info}" | sed --quiet '1p' | awk -F ' - ' '{print $2}')"
      _art="$(echo "${_info}" | sed --quiet '1p' | awk -F ' - ' '{print $1}')"
      # Shorten title/artist if longer than allotment
      if [ "$(echo "${_tit}" | wc --chars)" -gt "${SBP_MPD_MAXLEN}" ] ; then
        _tit="$(echo "${_tit}" \
          | awk "{print substr(\$0, 1, ${SBP_MPD_MAXLEN})}")…"
      fi
      if [ "$(echo "${_art}" | wc --chars)" -gt "${SBP_MPD_MAXLEN}" ] ; then
        _art="$(echo "${_art}" \
          | awk "{print substr(\$0, 1, ${SBP_MPD_MAXLEN})}")…"
      fi
      # Dim if paused
      if [ "${_sta}" = '[paused]' ] ; then
        _mute='true'
      fi
      # Format text
      _txt="${_tit}  ${_art}"
      ;;
    2) # Case; there is something happening; prob database update
      _sta="$(echo "${_info}" | sed --quiet '1p' | awk '{print $1}')"
      if echo "${_sta}" | grep --quiet 'Updating' ; then
        _txt='Database update…'
      else
        _txt=' '
      fi
      ;;
    1) # Case; empty playlist or no connection
      _mute='true'
      if echo "${_info}" | grep --quiet 'error' ; then
        _pre='ﱙ '
      elif echo "${_info}" | grep --quiet 'Empty' ; then
        _txt='Empty playlist'
      fi
      ;;
  esac
  # If lastfm is running; put up a suffix
  if pgrep mpdscribble >/dev/null ; then
    _suf=' '
  fi
  # Print JSON string
  _json="{\"prompt\":\"${_txt}\",\"accent\":\"${SBP_MPD_COLOR}\""
  _json="${_json},\"prefix\":\"${_pre}\",\"suffix\":\"${_suf}\",\"dim\":${_mute}"
  echo "${_json},\"tooltip\":\"${_tip}\"}"
}

# Listener loop
listener_loop () {
  # Use mpc idle function
  while : ; do
    mpc --quiet idle > /dev/null
    get_text
  done
}

# Main function
case $1 in
  actions) get_actions ;;
  once) get_text ;;
  *) get_text ; listener_loop ;;
esac
