#!/bin/dash
# vim:ft=sh
# Print current time continuosly
# Depends on: date (coreutils)

# Kill all descendents on exit
trap 'exit' INT TERM
trap 'kill 0' EXIT

# Default color
if [ -z "${SBP_CLOCK_COLOR}" ] ; then
    SBP_CLOCK_COLOR='indigo'
fi

# Click commands that can be overriden through environment vars
get_actions () {
# Function to generate action list
  # Left click
  if [ -z "${SBP_CLOCK_LEFTCLICK}" ] ; then
    _left='true'
  else
    _left="${SBP_CLOCK_LEFTCLICK}"
  fi
  # Right click
  if [ -z "${SBP_CLOCK_RIGHTCLICK}" ] ; then
    _right="true"
  else
    _right="${SBP_CLOCK_RIGHTCLICK}"
  fi
  # Middle click
  if [ -z "${SBP_CLOCK_MIDDLECLICK}" ] ; then
    _middle="true"
  else
    _middle="${SBP_CLOCK_MIDDLECLICK}"
  fi
  # Scroll up
  if [ -z "${SBP_CLOCK_SCROLLUP}" ] ; then
    _up='true'
  else
    _up="${SBP_CLOCK_SCROLLUP}"
  fi
  # Scroll down
  if [ -z "${SBP_CLOCK_SCROLLDOWN}" ] ; then
    _down='true'
  else
    _down="${SBP_CLOCK_SCROLLDOWN}"
  fi
  # Print json
  _jsonact="{\"middle\":\"${_middle}\""
  _jsonact="${_jsonact},\"left\":\"${_left}\",\"right\":\"${_right}\""
  echo "${_jsonact},\"up\":\"${_up}\",\"down\":\"${_down}\"}"
}

get_text() {
# Parse json text that has the fields;
# * accent: Accent color (not neccessary needed)
# * prompt: Text to display
# * prefix: Icon to display at beginning
# * suffix: Icon to display at end
# * tooltip: Expanded tooltip; maybe for future
# * dim: (Boolean) To dim module or not.
  # Change icon depending on the hour
  _hour="$(date '+%H')"
  if   [ "${_hour}" = '00' ] || [ "${_hour}" = '12' ] ; then
    _pre=" "
  elif [ "${_hour}" = '01' ] || [ "${_hour}" = '13' ] ; then
    _pre=" "
  elif [ "${_hour}" = '02' ] || [ "${_hour}" = '14' ] ; then
    _pre=" "
  elif [ "${_hour}" = '03' ] || [ "${_hour}" = '15' ] ; then
    _pre=" "
  elif [ "${_hour}" = '04' ] || [ "${_hour}" = '16' ] ; then
    _pre=" "
  elif [ "${_hour}" = '05' ] || [ "${_hour}" = '17' ] ; then
    _pre=" "
  elif [ "${_hour}" = '06' ] || [ "${_hour}" = '18' ] ; then
    _pre=" "
  elif [ "${_hour}" = '07' ] || [ "${_hour}" = '19' ] ; then
    _pre=" "
  elif [ "${_hour}" = '08' ] || [ "${_hour}" = '20' ] ; then
    _pre=" "
  elif [ "${_hour}" = '09' ] || [ "${_hour}" = '21' ] ; then
    _pre=" "
  elif [ "${_hour}" = '10' ] || [ "${_hour}" = '22' ] ; then
    _pre=" "
  elif [ "${_hour}" = '11' ] || [ "${_hour}" = '23' ] ; then
    _pre=" "
  else
    _pre=" "
  fi
  # Print JSON string
  _json="{\"prompt\":\"$(date '+%H:%M')\",\"accent\":\"${SBP_CLOCK_COLOR}\""
  _json="${_json},\"prefix\":\"${_pre}\",\"suffix\":\"\",\"dim\":false"
  echo "${_json},\"tooltip\":\"\"}"
}

polling_loop() {
# Poll the time every minute, starting from the start of every minute
  # The first wait should be until the end of the current minute
  sleep "$(( 1 + 60 - $(date '+%S') ))"
  while : ; do
    get_text
    sleep 60
  done
}

# Main function
case $1 in
  actions) get_actions ;;
  once) get_text ;;
  *) get_text ; polling_loop ;;
esac
